name: Go Game CI

on:
  push:
    paths:
      - 'go-game/**'
      - '.github/workflows/go-game-test.yml'
  pull_request:
    paths:
      - 'go-game/**'
      - '.github/workflows/go-game-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Test
        run: |
          mvn -B -q -pl go-game -am -DskipITs test || \
            (mvn -pl go-game -am -q -DskipITs help:effective-pom && cat ~/.m2/settings.xml && exit 1)
